/// The closed set of executable Gallery story identifiers.
public enum DesignOSStoryID: String, CaseIterable, Codable, Hashable, Sendable {
  case profileCustomization = "foundation.profile-customization"
  case colorRoles = "foundation.color-roles"
  case platformSemanticColor = "foundation.platform-semantic-color"
  case typographyRoles = "foundation.typography"
  case surfaceRoles = "foundation.surface-roles"
  case listRow = "component.list-row"
  case sidebarRow = "component.sidebar-row"
  case accessorySlotLayout = "primitive.accessory-slot-layout"
  case sectionContentLayout = "primitive.section-content-layout"
  case sidebarToolbarContent = "primitive.sidebar-toolbar-content"
  case symbolContent = "primitive.symbol-content"
  case buttonAndToolbarActions = "native.button-toolbar-actions"
  case contentUnavailable = "native.content-unavailable"
  case elevatedBackground = "native.elevated-background"
  case hierarchicalStyle = "native.hierarchical-style"
  case homeScreenQuickActions = "native.home-screen-quick-actions"
  case listSidebarAndDisclosure = "native.list-sidebar-disclosure"
  case materialAndGlassSurface = "native.material-glass-surface"
  case menuContextAndEditActions = "native.menu-context-edit-actions"
  case navigationTabsAndToolbars = "native.navigation-tabs-toolbars"
  case pickerAndDateColorInput = "native.picker-date-color-input"
  case presentationAndShare = "native.presentation-share"
  case progressSliderStepper = "native.progress-slider-stepper"
  case textSearchAndKeyboardInput = "native.text-search-keyboard-input"
  case systemDeviceChromeHost = "native.system-device-chrome-host"
  case extensionWidget = "extension.widget"
  case extensionControlWidget = "extension.control-widget"
  case omniactSettingsShell = "omniact.settings-shell"
  case omniactCommandRow = "omniact.command-row"
  case omniactHUDAutocompleteMaterial = "omniact.hud-autocomplete-material"
  case tocchienDictionarySearch = "tocchien.dictionary-search"
  case tocchienNavigationTabs = "tocchien.navigation-tabs"
  case tocchienChampionHeroNegativeControl = "tocchien.champion-hero-negative-control"
}
